# SonarQube — CampusFP Uniformes
sonar.projectKey=campusfp-uniformes
sonar.projectName=CampusFP Uniformes
sonar.projectVersion=1.0

# Modulos del monorepo
sonar.sources=backend/src,frontend/src,admin/src

sonar.exclusions=**/node_modules/**,**/target/**,**/build/**,**/*.test.*,**/dist/**

sonar.java.binaries=backend/target/classes
sonar.sourceEncoding=UTF-8

sonar.host.url=https://sonar.aulaforge.es
