CREATE TABLE configuracion_sitio (
    id_configuracion INT AUTO_INCREMENT PRIMARY KEY,
    logo_header_url VARCHAR(500) NOT NULL DEFAULT '/img/sportshop.jpg',
    logo_footer_url VARCHAR(500) NOT NULL DEFAULT '/img/sportshop.jpg',
    logo_login_url VARCHAR(500) NOT NULL DEFAULT '/img/sportshop.jpg',
    logo_home_url VARCHAR(500) NOT NULL DEFAULT '/img/sportshop.jpg',
    logo_admin_url VARCHAR(500) NOT NULL DEFAULT '/img/sportshop.jpg',
    bizum_telefono VARCHAR(50) NOT NULL DEFAULT '+34 600 000 000',
    bizum_banco_url VARCHAR(500) NOT NULL DEFAULT 'https://www.bizum.es/bancos-bizum/',
    transferencia_titular VARCHAR(150) NOT NULL DEFAULT 'Sportshop',
    transferencia_iban VARCHAR(50) NOT NULL DEFAULT 'ES00 0000 0000 0000 0000 0000',
    transferencia_concepto VARCHAR(255) NOT NULL DEFAULT 'Pedido {pedidoId} - Sportshop',
    transferencia_notas VARCHAR(500) NOT NULL DEFAULT 'Envia el justificante desde la pantalla de confirmacion del pedido.',
    email_bienvenida_asunto VARCHAR(255) NOT NULL DEFAULT 'Bienvenido a SportShop',
    email_bienvenida_cuerpo VARCHAR(4000) NOT NULL DEFAULT 'Hola {nombre}, tu cuenta se ha creado correctamente.',
    email_pedido_creado_asunto VARCHAR(255) NOT NULL DEFAULT 'Pedido {pedidoId} creado',
    email_pedido_creado_cuerpo VARCHAR(4000) NOT NULL DEFAULT 'Tu pedido {pedidoId} se ha registrado correctamente.',
    email_cambio_estado_asunto VARCHAR(255) NOT NULL DEFAULT 'Pedido {pedidoId}: {estado}',
    email_cambio_estado_cuerpo VARCHAR(4000) NOT NULL DEFAULT 'El estado de tu pedido {pedidoId} ha cambiado a {estado}.',
    email_cambio_password_asunto VARCHAR(255) NOT NULL DEFAULT 'Codigo de recuperacion de contrasena',
    email_cambio_password_cuerpo VARCHAR(4000) NOT NULL DEFAULT 'Tu codigo de recuperacion es {codigo}.',
    tarjeta_habilitada BOOLEAN NOT NULL DEFAULT FALSE,
    bizum_habilitado BOOLEAN NOT NULL DEFAULT TRUE,
    transferencia_habilitada BOOLEAN NOT NULL DEFAULT TRUE,
    mostrador_habilitado BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO configuracion_sitio (
    logo_header_url,
    logo_footer_url,
    logo_login_url,
    logo_home_url,
    logo_admin_url,
    bizum_telefono,
    bizum_banco_url,
    transferencia_titular,
    transferencia_iban,
    transferencia_concepto,
    transferencia_notas,
    email_bienvenida_asunto,
    email_bienvenida_cuerpo,
    email_pedido_creado_asunto,
    email_pedido_creado_cuerpo,
    email_cambio_estado_asunto,
    email_cambio_estado_cuerpo,
    email_cambio_password_asunto,
    email_cambio_password_cuerpo,
    tarjeta_habilitada,
    bizum_habilitado,
    transferencia_habilitada,
    mostrador_habilitado
)
VALUES (
    '/img/sportshop.jpg',
    '/img/sportshop.jpg',
    '/img/sportshop.jpg',
    '/img/sportshop.jpg',
    '/img/sportshop.jpg',
    '+34 600 000 000',
    'https://www.bizum.es/bancos-bizum/',
    'Sportshop',
    'ES00 0000 0000 0000 0000 0000',
    'Pedido {pedidoId} - Sportshop',
    'Envia el justificante desde la pantalla de confirmacion del pedido.',
    'Bienvenido a SportShop',
    'Hola {nombre}, tu cuenta se ha creado correctamente.',
    'Pedido {pedidoId} creado',
    'Tu pedido {pedidoId} se ha registrado correctamente.',
    'Pedido {pedidoId}: {estado}',
    'El estado de tu pedido {pedidoId} ha cambiado a {estado}.',
    'Codigo de recuperacion de contrasena',
    'Tu codigo de recuperacion es {codigo}.',
    FALSE,
    TRUE,
    TRUE,
    TRUE
);
