server {
    listen 80;
    server_name _;

    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";

    # ================= DEV =================

    location /dev/ {
        proxy_pass http://172.17.0.1:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept-Encoding "";

        sub_filter_once off;
        sub_filter 'src="/assets/' 'src="/dev/assets/';
        sub_filter 'href="/assets/' 'href="/dev/assets/';
        sub_filter 'href="/img/' 'href="/dev/img/';
        sub_filter 'src="/img/' 'src="/dev/img/';
    }

    location /dev/assets/ {
        proxy_pass http://172.17.0.1:8081/assets/;
    }

    location /dev/img/ {
        proxy_pass http://172.17.0.1:8081/img/;
    }

    location /dev/admin/ {
        proxy_pass http://172.17.0.1:8081/admin/;
        proxy_set_header Host $host;
        proxy_set_header Accept-Encoding "";

        sub_filter_once off;
        sub_filter 'src="/assets/' 'src="/dev/admin/assets/';
        sub_filter 'href="/assets/' 'href="/dev/admin/assets/';
        sub_filter 'src="/admin/img/' 'src="/dev/admin/img/';
        sub_filter 'href="/admin/img/' 'href="/dev/admin/img/';
    }

    location /dev/admin/assets/ {
        proxy_pass http://172.17.0.1:8081/admin/assets/;
    }

    location /dev/admin/img/ {
        proxy_pass http://172.17.0.1:8081/admin/img/;
    }

    # ================= PROD =================

    location / {
        proxy_pass http://frontend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://admin:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ /\. {
        deny all;
    }
}